from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
ASSETS_LABELED = ASSETS / "labeled"
ASSETS_CANDIDATES = ASSETS / "candidates"
ASSETS_RADICALS = ASSETS / "radicals"
DATA = ROOT / "data"
PROCESSED = DATA / "processed"
COMPONENTS = DATA / "components"
ANCHORS = DATA / "anchors"
STDSRC = DATA / "stdsrc"
GENERATED = DATA / "generated"
ASSEMBLED = DATA / "assembled"
PUZZLE = DATA / "puzzle"
PUZZLE_PIECES = PUZZLE / "pieces"
PUZZLE_CANDIDATES = PUZZLE / "candidates"
TARGET = DATA / "target"
OUTPUT = ROOT / "output"
REPORTS = OUTPUT / "reports"
FONTS = OUTPUT / "fonts"
MODELS = ROOT / "models"
QUEUE = ROOT / "queue"
DB_FILE = QUEUE / "font.db"
CONFIG_FILE = ROOT / "configs" / "default.yaml"
